# Prometheus Configuration for BeerFlow
#
# This configuration scrapes metrics from the BeerFlow API
# and can be used with the docker-compose monitoring stack

global:
  scrape_interval: 15s # Scrape targets every 15 seconds
  evaluation_interval: 15s # Evaluate rules every 15 seconds

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager)
  external_labels:
    monitor: 'beerflow-monitor'
    environment: 'production'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

# Load rules once and periodically evaluate them
rule_files:
  - 'alerts.yml'

# Scrape configurations
scrape_configs:
  # BeerFlow API metrics
  - job_name: 'beerflow-api'
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s
    static_configs:
      - targets:
          - 'host.docker.internal:3000' # For Docker on Mac/Windows
          # - 'localhost:3000' # For Docker on Linux
          # - 'beerflow-api:3000' # If running in same docker network
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'beerflow-api'

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node Exporter (system metrics)
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
